#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

/** @var \Interop\Container\ContainerInterface $container */
$container = require 'config/container.php';
$app = new Pawon\Console\Application($container);
$app->run();
